In [15]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

# 드라이버 설정
service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

# 페이지 열기
driver.get('https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx')




datas = []
for year in [2022, 2023, 2024, 2025, 2026]:
    select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
    select.select_by_value( str(year) )
    time.sleep(1)

    for page in range(1,4): # 1~3 페이지 반복
        try: # 2026년에만 3페이지가 있어서 오류 (오류방지)
            if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                btn.click()  # 버튼 클릭
                time.sleep(1)  # 페이지 로딩 기다리기
        except:
            break
    #=================================================================================================================
        html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
        soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
        result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
        result = result.select('tr')
    #==================================================================================================================
        for row in result:
            tds = row.select('td') # 한 행(tr)에서 모든 열(td)을 리스트로 가져옴
            name = tds[1].text.strip() # .text로 태그 안 텍스트만 추출 후, strip()으로 공백 제거 
            team = tds[2].text.strip()
            avg = float(tds[3].text.strip()) # 문자열로 오는 숫자를 float으로 변환
            pa = int(tds[4].text.strip())
            hit = int(tds[8].text.strip())
            two_base = int(tds[9].text.strip())
            three_base = int(tds[10].text.strip())
            home_run = int(tds[11].text.strip())
            rbi = int(tds[13].text.strip())

            data = {
                'year' : year,
                'name' : name,
                'team' : team,
                'avg' : avg,
                'pa' : pa,
                'hit' : hit,
                'two_base' : two_base,
                'three_base' : three_base,
                'home_run' : home_run,
                'rbi' : rbi
            }

            datas.append(data)

driver.quit()

df_batter = pd.DataFrame(datas)
df_batter['year'] = df_batter['year'].astype('category')
df_batter

     year name team    avg   pa  hit  two_base  three_base  home_run  rbi
0    2022  이정후   키움  0.349  142  193        36          10        23  113
1    2022  피렐라   삼성  0.342  141  192        33           4        28  109
2    2022  박건우   NC  0.336  111  137        18           1        10   61
3    2022  이대호   롯데  0.331  142  179        23           0        23  101
4    2022  나성범  KIA  0.320  144  180        39           2        21   97
..    ...  ...  ...    ...  ...  ...       ...         ...       ...  ...
246  2026  이재현   삼성  0.077    4    1         0           0         0    1
247  2026  한승택   KT  0.077    4    1         0           0         0    1
248  2026  김재환  SSG  0.071    4    1         0           0         1    4
249  2026  오지환   LG  0.067    4    1         1           0         0    3
250  2026  양의지   두산  0.059    4    1         0           0         0    0

[251 rows x 10 columns]

In [18]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

def crawl_batter_attack():
    # 드라이버 설정
    service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
    driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

    # 페이지 열기
    driver.get('https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx')

    datas = []

    for year in [2022, 2023, 2024, 2025, 2026]:
        
        select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
        select.select_by_value( str(year) )
        time.sleep(1)
        
        for position, value in [('포수', '2'), ('내야수', '3,4,5,6'), ('외야수', '7,8,9')]:
            select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlPos_ddlPos'))
            select.select_by_value(value)
            time.sleep(1)

            for page in range(1,6): # 1~5 페이지 반복
                try: 
                    if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                        btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                        btn.click()  # 버튼 클릭
                        time.sleep(1)  # 페이지 로딩 기다리기
                except:
                    break
    #=================================================================================================================
                html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
                soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
                result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
                result = result.select('tr')
    #==================================================================================================================

                columns = ['name', 'team', 'avg', 'game_cnt', 'pa', 'ab', 'r', 'hit', '2b', '3b', 'home_run', 'tb', 'rbi', 'sac', 'sf' ]

                for row in result:
                    tds = row.select('td')
                    values = [td.text.strip() for td in tds[1:]]
                    data = {'year' : year, 'position' : position}
                    data.update( dict(zip(columns, values)) )
                    datas.append(data)
    driver.quit()

    df_batter_atteck = pd.DataFrame(datas)
    return df_batter_atteck
    

df_batter_atteck = crawl_batter_attack()
df_batter_atteck

,year,position,name,team,avg,game_cnt,pa,ab,r,hit,2b,3b,home_run,tb,rbi,sac,sf
0,2022,포수,이병헌,삼성,0.750,3,4,4,1,3,1,0,0,4,1,0,0
1,2022,포수,권다결,KIA,0.500,2,2,2,0,1,0,0,0,1,1,0,0
2,2022,포수,김재성,삼성,0.335,63,185,161,16,54,10,0,3,73,26,1,3
3,2022,포수,안승한,두산,0.333,30,39,36,5,12,3,0,0,15,8,1,0
4,2022,포수,김선우,KIA,0.333,3,4,3,1,1,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1052,2026,외야수,장두성,롯데,0.000,4,5,4,0,0,0,0,0,0,0,1,0
1053,2026,외야수,박재현,KIA,-,3,0,0,1,0,0,0,0,0,0,0,0
1054,2026,외야수,이창진,KIA,0.000,1,2,2,0,0,0,0,0,0,0,0,0
1055,2026,외야수,박수종,키움,-,2,0,0,1,0,0,0,0,0,0,0,0
1056,2026,외야수,이형종,키움,0.000,2,8,4,2,0,0,0,0,0,0,0,0

In [ ]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

def crawl_batter_defence():
    # 드라이버 설정
    service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
    driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

    # 페이지 열기
    driver.get('https://www.koreabaseball.com/Record/Player/Defense/Basic.aspx')

    datas = []

    for year in [2022, 2023, 2024, 2025, 2026]:
        
        select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
        select.select_by_value( str(year) )
        time.sleep(1)
        
        for position, value in [('포수', '2'), ('내야수', '3,4,5,6'), ('외야수', '7,8,9')]:
            select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlPos_ddlPos'))
            select.select_by_value(value)
            time.sleep(1)

            for page in range(1,6): # 1~5 페이지 반복
                try: 
                    if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                        btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                        btn.click()  # 버튼 클릭
                        time.sleep(1)  # 페이지 로딩 기다리기
                except:
                    break
    #=================================================================================================================
                html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
                soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
                result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
                result = result.select('tr')
    #==================================================================================================================

                columns = ['name', 'team', 'detail_position', 'gama_starter', 'inning_defence', 'error', 'pko', 'assist', 'double_play', 'fpct', 'pb', 'sb', 'cs', 'cs%']

                for row in result:
                    tds = row.select('td')
                    values = [td.text.strip() for td in tds[1:]]
                    data = {'year' : year, 'position' : position}
                    data.update( dict(zip(columns, values)) )
                    datas.append(data)
    driver.quit()

    df_batter_defence = pd.DataFrame(datas)
    return df_batter_defence
    

df_batter_defence = crawl_batter_defence()
df_batter_defence

,year,position,name,team,detail_position,gama_starter,inning_defence,error,pko,assist,double_play,fpct,pb,sb,cs,cs%
0,2022,포수,이지영,키움,포수,137,102,994 2/3,11,0,818,77,9,0.988,4,67
1,2022,포수,유강남,LG,포수,134,115,1008 1/3,7,1,821,71,8,0.992,4,91
2,2022,포수,박세혁,두산,포수,126,110,884,5,0,689,68,10,0.993,7,74
3,2022,포수,박동원,KIA,포수,114,98,865,5,2,703,71,8,0.994,5,40
4,2022,포수,최재훈,한화,포수,106,101,853 2/3,3,1,644,78,10,0.996,7,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,2026,외야수,조수행,두산,우익수,1,0,3,0,0,1,0,0,1.000,0,0
1399,2026,외야수,카메론,두산,우익수,1,1,3,0,0,0,0,0,-,0,0
1400,2026,외야수,박수종,키움,좌익수,1,0,1,0,0,0,0,0,-,0,0
1401,2026,외야수,박수종,키움,중견수,1,0,1,0,0,1,0,0,1.000,0,0
1402,2026,외야수,박찬혁,키움,우익수,1,1,8,0,0,1,0,0,1.000,0,0

In [ ]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

def crawl_pitcher():
    # 드라이버 설정
    service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
    driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

    # 페이지 열기
    driver.get('https://www.koreabaseball.com/Record/Player/PitcherBasic/Basic1.aspx')

    datas = []

    for year in [2022, 2023, 2024, 2025, 2026]:
        
        select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
        select.select_by_value( str(year) )
        time.sleep(1)
        
        for page in range(1,3): # 1~2 페이지 반복
            try: 
                if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                    btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                    btn.click()  # 버튼 클릭
                    time.sleep(1)  # 페이지 로딩 기다리기
            except:
                break
#=================================================================================================================
            html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
            soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
            result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
            result = result.select('tr')
#==================================================================================================================

            columns = ['name', 'team', 'era', 'game_cnt', 'inning_defence', 'win', 'lose', 'save', 'hold',
                        'wpct', 'inning', 'hit', 'home_run', 'bb', 'hbp', 'kk', 'r', 'er', 'whip']

            for row in result:
                tds = row.select('td')
                values = [td.text.strip() for td in tds[1:]]
                data = {'year' : year}
                data.update( dict(zip(columns, values)) )
                datas.append(data)
    driver.quit()

    df_pitcher = pd.DataFrame(datas)
    return df_pitcher
    

df_pitcher = crawl_pitcher()
df_pitcher

,year,name,team,era,game_cnt,inning_defence,win,lose,save,hold,wpct,inning,hit,home_run,bb,hbp,kk,r,er
0,2022,안우진,키움,2.11,30,15,8,0,0,0.652,196,131,4,55,4,224,51,46,0.95
1,2022,김광현,SSG,2.13,28,13,3,0,0,0.813,173 1/3,141,10,45,5,153,48,41,1.07
2,2022,플럿코,LG,2.39,28,15,5,0,0,0.750,162,125,13,38,2,149,53,43,1.01
3,2022,수아레즈,삼성,2.49,30,6,8,0,0,0.429,173 2/3,151,7,50,4,159,61,48,1.16
4,2022,켈리,LG,2.54,27,16,4,0,0,0.800,166 1/3,144,10,35,2,153,50,47,1.08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2026,양현종,KIA,6.75,1,0,1,0,0,0.000,4,3,0,4,0,4,3,3,1.75
110,2026,에르난데스,한화,7.71,1,0,0,0,0,-,4 2/3,4,0,4,0,3,4,4,1.71
111,2026,곽빈,두산,9.00,1,0,0,0,0,-,4,5,2,2,0,5,4,4,1.75
112,2026,타케다,SSG,9.64,1,0,1,0,0,0.000,4 2/3,9,0,1,0,5,5,5,2.14
113,2026,화이트,SSG,11.25,1,0,0,0,0,-,4,9,0,2,0,4,5,5,2.75

In [17]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

def crawl_team():
    # 드라이버 설정
    service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
    driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

    # 페이지 열기
    driver.get('https://www.koreabaseball.com/Record/TeamRank/TeamRank.aspx')

    datas = []

    for year in [2022, 2023, 2024, 2025, 2026]:
        
        select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlYear'))  # 드롭다운 요소 찾기
        select.select_by_value( str(year) )
        time.sleep(1)
        
#=================================================================================================================
        html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
        soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
        result = soup.select_one('#cphContents_cphContents_cphContents_udpRecord > table > tbody')
        result = result.select('tr')
#==================================================================================================================

        columns = ['rank', 'team', 'game', 'win', 'lose', 'draw', 'winning_rate', 'games_behind', 'recent10' , 'inarow', 'home', 'away']

        for row in result:
            tds = row.select('td')
            values = [td.text.strip() for td in tds[:]]
            data = {'year' : year}
            data.update( dict(zip(columns, values)) )
            datas.append(data)
    driver.quit()

    df_team = pd.DataFrame(datas)
    return df_team
    

df_team = crawl_team()
df_team

,year,rank,team,game,win,lose,draw,winning_rate,games_behind,recent10,inarow,home,away
0,2022,1,SSG,144,88,52,4,0.629,0,4승0무6패,4패,49-0-23,39-4-29
1,2022,2,키움,144,80,62,2,0.563,9,5승0무5패,1승,39-1-32,41-1-30
2,2022,3,LG,144,87,55,2,0.613,2,4승0무6패,1승,38-1-33,49-1-22
3,2022,4,KT,144,80,62,2,0.563,9,7승0무3패,1패,40-1-31,40-1-31
4,2022,5,KIA,144,70,73,1,0.490,19.5,7승0무3패,1패,31-0-41,39-1-32
5,2022,6,NC,144,67,74,3,0.475,21.5,6승0무4패,1패,35-3-34,32-0-40
6,2022,7,삼성,144,66,76,2,0.465,23,6승0무4패,2승,33-2-37,33-0-39
7,2022,8,롯데,144,64,76,4,0.457,24,5승0무5패,1승,27-3-42,37-1-34
8,2022,9,두산,144,60,82,2,0.423,29,4승0무6패,2패,29-1-42,31-1-40
9,2022,10,한화,144,46,96,2,0.324,43,3승0무7패,1패,28-0-44,18-2-52
10,2023,1,LG,144,86,56,2,0.606,0,5승0무5패,1승,45-1-25,41-1-31
11,2023,2,KT,144,79,62,3,0.560,6.5,6승0무4패,3승,41-2-30,38-1-32
12,2023,3,SSG,144,76,65,3,0.539,9.5,8승0무2패,2승,39-2-32,37-1-33
13,2023,4,NC,144,75,67,2,0.528,11,5승0무5패,2패,41-1-29,34-1-38
14,2023,5,두산,144,74,68,2,0.521,12,4승0무6패,3패,37-1-35,37-1-33
15,2023,6,KIA,144,73,69,2,0.514,13,7승0무3패,2승,38-2-31,35-0-38
16,2023,7,롯데,144,68,76,0,0.472,19,4승0무6패,1승,38-0-35,30-0-41
17,2023,8,삼성,144,61,82,1,0.427,25.5,4승0무6패,1패,32-0-39,29-1-43
18,2023,9,한화,144,58,80,6,0.420,26,3승0무7패,1패,32-1-40,26-5-40
19,2023,10,키움,144,58,83,3,0.411,27.5,5승0무5패,2패,33-2-36,25-1-47
20,2024,1,KIA,144,87,55,2,0.613,0,5승0무5패,2승,42-1-30,45-1-25
21,2024,2,삼성,144,78,64,2,0.549,9,3승0무7패,1패,41-0-32,37-2-32
22,2024,3,LG,144,76,66,2,0.535,11,7승0무3패,2승,39-1-33,37-1-33
23,2024,4,두산,144,74,68,2,0.521,13,8승0무2패,4승,39-1-31,35-1-37
24,2024,5,KT,144,72,70,2,0.507,15,5승0무5패,3승,34-1-36,38-1-34
25,2024,6,SSG,144,72,70,2,0.507,15,8승0무2패,4승,35-1-35,37-1-35
26,2024,7,롯데,144,66,74,4,0.471,20,4승0무6패,1승,37-3-31,29-1-43
27,2024,8,한화,144,66,76,2,0.465,21,5승0무5패,2패,30-2-39,36-0-37
28,2024,9,NC,144,61,81,2,0.430,26,2승0무8패,2패,34-0-39,27-2-42
29,2024,10,키움,144,58,86,0,0.403,30,1승0무9패,5패,32-0-41,26-0-45
30,2025,1,LG,144,85,56,3,0.603,0,4승0무6패,3패,41-1-29,44-2-27
31,2025,2,한화,144,83,57,4,0.593,1.5,5승1무4패,1패,44-2-27,39-2-30
32,2025,3,SSG,144,75,65,4,0.536,9.5,6승0무4패,2패,38-4-31,37-0-34
33,2025,4,삼성,144,74,68,2,0.521,11.5,7승0무3패,1패,41-0-30,33-2-38
34,2025,5,NC,144,71,67,6,0.514,12.5,9승0무1패,9승,36-1-34,35-5-33
35,2025,6,KT,144,71,68,5,0.511,13,5승1무4패,1승,36-2-35,35-3-33
36,2025,7,롯데,144,66,72,6,0.478,17.5,2승0무8패,3패,35-4-34,31-2-38
37,2025,8,KIA,144,65,75,4,0.464,19.5,4승0무6패,2승,35-2-34,30-2-41
38,2025,9,두산,144,61,77,6,0.442,22.5,5승0무5패,2승,29-4-40,32-2-37
39,2025,10,키움,144,47,93,4,0.336,37.5,3승0무7패,5패,23-2-46,24-2-47
40,2026,1,KT,4,4,0,0,1.000,0,4승0무0패,4승,0-0-0,4-0-0
41,2026,2,SSG,4,3,1,0,0.750,1,3승0무1패,1패,3-0-1,0-0-0
42,2026,2,NC,4,3,1,0,0.750,1,3승0무1패,2승,3-0-1,0-0-0
43,2026,4,한화,4,2,2,0,0.500,2,2승0무2패,2패,2-0-2,0-0-0
44,2026,4,롯데,4,2,2,0,0.500,2,2승0무2패,2패,0-0-0,2-0-2
45,2026,6,삼성,4,1,2,1,0.333,2.5,1승1무2패,1승,1-1-2,0-0-0
46,2026,6,두산,4,1,2,1,0.333,2.5,1승1무2패,1패,0-0-0,1-1-2
47,2026,8,LG,4,1,3,0,0.250,3,1승0무3패,1승,1-0-3,0-0-0
48,2026,8,KIA,4,1,3,0,0.250,3,1승0무3패,1패,0-0-0,1-0-3
49,2026,8,키움,4,1,3,0,0.250,3,1승0무3패,1승,0-0-0,1-0-3

In [19]:
df_batter_atteck.to_csv('batter_atteck.csv', index = False, encoding='utf-8')
df_batter_defence.to_csv('batter_defence.csv', index = False, encoding='utf-8')
df_pitcher.to_csv('pitcher.csv', index = False, encoding='utf-8')
df_team.to_csv('team.csv', index = False, encoding='utf-8')

In [8]:
import pandas as pd
df = pd.read_csv('data_csv/batter_offence.csv',encoding='utf-8')
df['year'] = df['year'].astype('category')
df.to_csv('data_csv/batter_offence.csv', index=False)

In [9]:
df = pd.read_csv('data_csv/batter_offence.csv',encoding='utf-8')
df['year'].dtype

dtype('int64')

In [ ]:
print(df_pitcher.dtypes)
print(df_pitcher.isnull().sum())
print(df_pitcher.describe())

year        category
name          object
team          object
era          float64
game_cnt       int64
win            int64
lose           int64
save           int64
hold           int64
ip           float64
hitted         int64
home_run       int64
BB             int64
KK             int64
dtype: object
year        0
name        0
team        0
era         0
game_cnt    0
win         0
lose        0
save        0
hold        0
ip          0
hitted      0
home_run    0
BB          0
KK          0
dtype: int64
              era    game_cnt         win        lose        save        hold  \
count  111.000000  111.000000  111.000000  111.000000  111.000000  111.000000
mean     3.428378   21.324324    8.108108    5.846847    0.009009    0.036036
std      1.363295   12.436868    5.319520    4.121337    0.094916    0.187225
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000
25%      2.690000    1.500000    1.000000    1.000000    0.000000    0.000000
50%      3.540000   28.000000   10.000000    7.000000    0.000000    0.000000
75%      4.145000   30.000000   12.000000    8.500000    0.000000    0.000000
max      7.710000   32.000000   20.000000   14.000000    1.000000    1.000000

               ip      hitted    home_run          BB          KK
count  111.000000  111.000000  111.000000  111.000000  111.000000
mean   122.240240  117.027027    9.441441   34.486486  108.081081
std     72.648610   70.733618    7.025518   23.100517   68.992639
min      4.000000    2.000000    0.000000    0.000000    1.000000
25%      6.000000    7.000000    1.000000    5.000000    6.500000
50%    157.333333  149.000000   10.000000   39.000000  129.000000
75%    171.500000  169.500000   14.500000   50.000000  155.000000
max    197.333333  210.000000   28.000000   84.000000  252.000000

In [3]:
import pandas as pd
df = pd.read_csv(r'data_csv\team.csv')

df = df.rename(columns=
               {
                   'rank' : 'ranking'
               })

print(df.head())
df.to_csv('data_csv/team.csv', index=False)

   year  ranking team  game  win  lose  draw  winning_rate  games_behind  \
0  2022        1  SSG   144   88    52     4         0.629           0.0
1  2022        2   키움   144   80    62     2         0.563           9.0
2  2022        3   LG   144   87    55     2         0.613           2.0
3  2022        4   KT   144   80    62     2         0.563           9.0
4  2022        5  KIA   144   70    73     1         0.490          19.5

  recent10 inarow     home     away
0   4승0무6패     4패  49-0-23  39-4-29
1   5승0무5패     1승  39-1-32  41-1-30
2   4승0무6패     1승  38-1-33  49-1-22
3   7승0무3패     1패  40-1-31  40-1-31
4   7승0무3패     1패  31-0-41  39-1-32