In [15]:
import requests
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
from selenium.webdriver.common.by import By  # By.ID 사용하기 위해 임포트
import time
from selenium.webdriver.support.ui import Select # 드롭다운 다루는 클래스 임포트

# 드라이버 설정
service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

# 페이지 열기
driver.get('https://www.koreabaseball.com/Record/Player/HitterBasic/Basic1.aspx')




datas = []
for year in [2022, 2023, 2024, 2025, 2026]:
    select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
    select.select_by_value( str(year) )
    time.sleep(1)

    for page in range(1,4): # 1~3 페이지 반복
        try: # 2026년에만 3페이지가 있어서 오류 (오류방지)
            if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                btn.click()  # 버튼 클릭
                time.sleep(1)  # 페이지 로딩 기다리기
        except:
            break
    #=================================================================================================================
        html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
        soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
        result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
        result = result.select('tr')
    #==================================================================================================================
        for row in result:
            tds = row.select('td') # 한 행(tr)에서 모든 열(td)을 리스트로 가져옴
            name = tds[1].text.strip() # .text로 태그 안 텍스트만 추출 후, strip()으로 공백 제거 
            team = tds[2].text.strip()
            avg = float(tds[3].text.strip()) # 문자열로 오는 숫자를 float으로 변환
            pa = int(tds[4].text.strip())
            hit = int(tds[8].text.strip())
            two_base = int(tds[9].text.strip())
            three_base = int(tds[10].text.strip())
            home_run = int(tds[11].text.strip())
            rbi = int(tds[13].text.strip())

            data = {
                'year' : year,
                'name' : name,
                'team' : team,
                'avg' : avg,
                'pa' : pa,
                'hit' : hit,
                'two_base' : two_base,
                'three_base' : three_base,
                'home_run' : home_run,
                'rbi' : rbi
            }

            datas.append(data)

driver.quit()

df_batter = pd.DataFrame(datas)
df_batter['year'] = df_batter['year'].astype('category')
df_batter

     year name team    avg   pa  hit  two_base  three_base  home_run  rbi
0    2022  이정후   키움  0.349  142  193        36          10        23  113
1    2022  피렐라   삼성  0.342  141  192        33           4        28  109
2    2022  박건우   NC  0.336  111  137        18           1        10   61
3    2022  이대호   롯데  0.331  142  179        23           0        23  101
4    2022  나성범  KIA  0.320  144  180        39           2        21   97
..    ...  ...  ...    ...  ...  ...       ...         ...       ...  ...
246  2026  이재현   삼성  0.077    4    1         0           0         0    1
247  2026  한승택   KT  0.077    4    1         0           0         0    1
248  2026  김재환  SSG  0.071    4    1         0           0         1    4
249  2026  오지환   LG  0.067    4    1         1           0         0    3
250  2026  양의지   두산  0.059    4    1         0           0         0    0

[251 rows x 10 columns]

In [18]:
def convert_ip(ip_str):
    try:
        ip_int, ip_float = ip_str.split()
        ip_int = float(ip_int)
        numerator, denominator = map(int, ip_float.split('/') )
        ip_float = float( numerator / denominator )
        return ip_int + ip_float
    except:
        ip_int = float(ip_str)
        return ip_int





# 드라이버 설정
service = Service( ChromeDriverManager().install() ) # 크롬 드라이버 자동 설치
driver = webdriver.Chrome(service=service) # 실제 브라우저 실행

# 페이지 열기
driver.get('https://www.koreabaseball.com/Record/Player/PitcherBasic/Basic1.aspx')




datas = []
for year in [2022, 2023, 2024, 2025, 2026]:
    select = Select(driver.find_element(By.ID, 'cphContents_cphContents_cphContents_ddlSeason_ddlSeason'))  # 드롭다운 요소 찾기
    select.select_by_value( str(year) )
    time.sleep(1)

    for page in range(1,2): # 1~3 페이지 반복
        try: 
            if page > 1: # 1페이지는 이미 열려있으니까 클릭 건너뜀
                btn = driver.find_element(By.ID, f'cphContents_cphContents_cphContents_ucPager_btnNo{page}')  # page 변수로 id 동적 생성
                btn.click()  # 버튼 클릭
                time.sleep(1)  # 페이지 로딩 기다리기
        except:
            break


    #=================================================================================================================
        html = driver.page_source # 현재 브라우저에 렌더링 된 HTML 전체 가져옴
        soup = BeautifulSoup(html, 'lxml') # lxml : 빠른 파서
        result = soup.select_one('#cphContents_cphContents_cphContents_udpContent > div.record_result > table > tbody')
        result = result.select('tr')
    #==================================================================================================================
        for row in result:
            tds = row.select('td') # 한 행(tr)에서 모든 열(td)을 리스트로 가져옴
            name = tds[1].text.strip() # .text로 태그 안 텍스트만 추출 후, strip()으로 공백 제거 
            team = tds[2].text.strip()
            era = float(tds[3].text.strip()) # 문자열로 오는 숫자를 float으로 변환
            game_cnt = int(tds[4].text.strip())
            win = int(tds[5].text.strip())
            lose = int(tds[6].text.strip())
            save = int(tds[7].text.strip())
            hold = int(tds[8].text.strip())
            ip = tds[10].text.strip()
            hitted = int(tds[11].text.strip())
            home_run = int(tds[12].text.strip())
            base_on_balls = int(tds[13].text.strip())
            strike_out = int(tds[15].text.strip())


            data = {
                'year' : year,
                'name' : name,
                'team' : team,
                'era' : era,
                'game_cnt' : game_cnt,
                'win' : win,
                'lose' : lose,
                'save' : save,
                'hold' : hold,
                'ip' : convert_ip(ip),
                'hitted' : hitted,
                'home_run' : home_run,
                'BB' : base_on_balls,
                'KK' : strike_out
            }

            datas.append(data)

driver.quit()

df_pitcher = pd.DataFrame(datas)
df_pitcher['year'] = df_pitcher['year'].astype('category')
df_pitcher

,year,name,team,era,game_cnt,win,lose,save,hold,ip,hitted,home_run,BB,KK
0,2022,안우진,키움,2.11,30,15,8,0,0,196.000000,131,4,55,224
1,2022,김광현,SSG,2.13,28,13,3,0,0,173.333333,141,10,45,153
2,2022,플럿코,LG,2.39,28,15,5,0,0,162.000000,125,13,38,149
3,2022,수아레즈,삼성,2.49,30,6,8,0,0,173.666667,151,7,50,159
4,2022,켈리,LG,2.54,27,16,4,0,0,166.333333,144,10,35,153
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,2026,고영표,KT,5.40,1,0,0,0,0,5.000000,7,1,1,7
107,2026,사우어,KT,5.40,1,1,0,0,0,5.000000,5,1,5,1
108,2026,윤산흠,한화,6.75,4,0,0,0,0,4.000000,4,0,4,4
109,2026,양현종,KIA,6.75,1,0,1,0,0,4.000000,3,0,4,4
110,2026,에르난데스,한화,7.71,1,0,0,0,0,4.666667,4,0,4,3

In [16]:
print(df_batter.dtypes)
print(df_batter.isnull().sum())
print(df_batter.describe())

year          category
name            object
team            object
avg            float64
pa               int64
hit              int64
two_base         int64
three_base       int64
home_run         int64
rbi              int64
dtype: object
year          0
name          0
team          0
avg           0
pa            0
hit           0
two_base      0
three_base    0
home_run      0
rbi           0
dtype: int64
              avg          pa         hit    two_base  three_base    home_run  \
count  251.000000  251.000000  251.000000  251.000000  251.000000  251.000000
mean     0.261291   89.820717   84.286853   15.015936    1.266932    9.561753
std      0.043214   59.366352   57.767858   10.922625    1.925737    9.331193
min      0.059000    3.000000    1.000000    0.000000    0.000000    0.000000
25%      0.249000    4.000000    5.000000    1.000000    0.000000    1.000000
50%      0.266000  125.000000  109.000000   18.000000    0.000000    7.000000
75%      0.281000  134.000000  125.000000   24.000000    2.000000   16.000000
max      0.349000  144.000000  193.000000   42.000000   10.000000   35.000000

              rbi
count  251.000000
mean    45.055777
std     33.206217
min      0.000000
25%      4.000000
50%     49.000000
75%     69.000000
max    113.000000

In [19]:
print(df_pitcher.dtypes)
print(df_pitcher.isnull().sum())
print(df_pitcher.describe())

year        category
name          object
team          object
era          float64
game_cnt       int64
win            int64
lose           int64
save           int64
hold           int64
ip           float64
hitted         int64
home_run       int64
BB             int64
KK             int64
dtype: object
year        0
name        0
team        0
era         0
game_cnt    0
win         0
lose        0
save        0
hold        0
ip          0
hitted      0
home_run    0
BB          0
KK          0
dtype: int64
              era    game_cnt         win        lose        save        hold  \
count  111.000000  111.000000  111.000000  111.000000  111.000000  111.000000
mean     3.428378   21.324324    8.108108    5.846847    0.009009    0.036036
std      1.363295   12.436868    5.319520    4.121337    0.094916    0.187225
min      0.000000    1.000000    0.000000    0.000000    0.000000    0.000000
25%      2.690000    1.500000    1.000000    1.000000    0.000000    0.000000
50%      3.540000   28.000000   10.000000    7.000000    0.000000    0.000000
75%      4.145000   30.000000   12.000000    8.500000    0.000000    0.000000
max      7.710000   32.000000   20.000000   14.000000    1.000000    1.000000

               ip      hitted    home_run          BB          KK
count  111.000000  111.000000  111.000000  111.000000  111.000000
mean   122.240240  117.027027    9.441441   34.486486  108.081081
std     72.648610   70.733618    7.025518   23.100517   68.992639
min      4.000000    2.000000    0.000000    0.000000    1.000000
25%      6.000000    7.000000    1.000000    5.000000    6.500000
50%    157.333333  149.000000   10.000000   39.000000  129.000000
75%    171.500000  169.500000   14.500000   50.000000  155.000000
max    197.333333  210.000000   28.000000   84.000000  252.000000